# -*- mode: ruby -*-
# vi: set ft=ruby :
HOST_SHARE_DIR = "./share/src".freeze
VAGRANT_HOME = "/home/vagrant".freeze
GUEST_SHARED_DIR = "#{VAGRANT_HOME}/go/src".freeze
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "forwarded_port", guest: 80, host: 12080
  # Shared directory between HOST and GUEST
  config.vm.synced_folder HOST_SHARE_DIR, GUEST_SHARED_DIR
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
    # Syncronize time between host and guest
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/VMMDev/0/Config/GetHostTimeDisabled", 0]
  end
  config.vm.provision "shell", inline: <<-SHELL
    echo "*************** START: setup general package *******************"
    apt update
    apt -y install tree lynx ctags install unzip man tig
    echo "*************** COMPLETE: setup general package *******************"
    echo ""
    echo "*************** START: install git *******************"
    apt -y install libcurl4-gnutls-dev libexpat1-dev gettext libz-dev libssl-dev autoconf asciidoc xmlto docbook2x make gcc
    wget https://github.com/git/git/archive/v2.20.1.tar.gz

    tar -zxf v2.20.1.tar.gz
    cd git-2.20.1
    make configure
    ./configure --prefix=/usr
    make all doc info
    make install install-doc install-html install-info
    cd ../
    rm -f v2.20.1.tar.gz
    rm -rf git-2.20.1
    echo "*************** COMPLETE: install git *******************"
    echo ""
    echo "*************** start setup diff-highlight *******************"
    cd /opt/
    git clone https://github.com/git/git.git
    cd git/contrib/diff-highlight
    make
    ln -s /opt/git/contrib/diff-highlight/diff-highlight /usr/bin/
    echo "*************** complete setup git *******************"
    echo ""
    echo "*************** start setup zsh *******************"
    apt -y install zsh
    chsh -s /bin/zsh vagrant
    echo "*************** complete setup zsh *******************"
    echo ""
    echo "*************** start setup dotfies *******************"
    if [ -e #{VAGRANT_HOME}/dotfiles ]; then
      cd #{VAGRANT_HOME}/dotfiles && git pull
    else
      git clone https://github.com/gimKondo/dotfiles.git #{VAGRANT_HOME}/dotfiles
    fi
    chown -R vagrant #{VAGRANT_HOME}/dotfiles
    chmod +x #{VAGRANT_HOME}/dotfiles/install.sh
    #{VAGRANT_HOME}/dotfiles/install.sh #{VAGRANT_HOME}
    echo "*************** complete setup dotfies *******************"
    echo ""
    echo "*************** start install vim *******************"
    apt remove --purge vim vim-runtime vim-common
    apt install -y build-essential ncurses-dev lua5.2 lua5.2-dev luajit python-dev python3-dev ruby-dev
    cd /opt/
    git clone https://github.com/vim/vim
    cd vim/
    ./configure --with-features=huge --enable-multibyte --enable-luainterp=dynamic --enable-gpm --enable-cscope --enable-fontset --enable-fail-if-missing --prefix=/usr/local --enable-pythoninterp=dynamic --enable-python3interp=dynamic --enable-rubyinterp=dynamic
    make
    make install
    echo "*************** complete install vim *******************"
    echo ""
    echo "*************** start get tmux *******************"
    apt install -y automake libevent-dev
    cd /opt/
    git clone https://github.com/tmux/tmux
    cd ./tmux/
    ./autogen.sh
    ./configure --prefix=/usr/local
    make
    make install
    echo "*************** complete get tmux *******************"
    echo ""
    echo "*************** start get goenv *******************"
    if [ -e #{VAGRANT_HOME}/.goenv ]; then
      cd #{VAGRANT_HOME}/.goenv && git pull
    else
      git clone https://github.com/syndbg/goenv.git #{VAGRANT_HOME}/.goenv
    fi
    chown -R vagrant #{VAGRANT_HOME}/.goenv
    echo "*************** complete get goenv *******************"
    echo ""
    echo "*************** START: change owner of shared directory *******************"
    chown -R vagrant #{VAGRANT_HOME}/go/
    echo "*************** COMPLETE: change owner of shared directory *******************"
    echo ""
  SHELL
end
